set resource group process mode:
  image: curlimages/curl:latest
  stage: .pre
  script:
    - > 
        curl --request PUT --data "process_mode=oldest_first" --header "PRIVATE-TOKEN: ${CI_JOB_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/resource_groups/trigger-test-repo"

        curl --request PUT --data "process_mode=oldest_first" --header "PRIVATE-TOKEN: ${CI_JOB_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/resource_groups/integration-test"

unit test:
  image: python:3.11-alpine
  stage: test
  before_script:
    - apk update && apk add git
    - pip install -U pip setuptools wheel && pip install -r requirements.txt
  script:
    - python -m unittest

integration test:
  resource_group: trigger-test-repo
  trigger:
    include:
      - local: .gitlab-ci-test-repo.yml
    forward:
      pipeline_variables: true
    strategy: depend
  parallel:
    matrix:
      - TEST_INPUT_DIR: "test/integration_test_inputs/mkdocs-material"
      - TEST_INPUT_DIR: "test/integration_test_inputs/no-input"
