integration test:
  resource_group: push-to-test-repo
  trigger:
    include:
      - local: .gitlab-ci-test-repo.yml

unit test:
  image: python:3.11-alpine
  stage: test
  before_script:
    - apk update && apk add git
    - pip install -U pip setuptools wheel && pip install -r requirements.txt
  script:
    - python -m unittest
