generate copies:
  image: python:3.11
  stage: build
  before_script:
    - pip install -U pip setuptools wheel && pip install -r requirements.txt
    - . utils.sh
  script:
    - copier copy src dst
    - cp test/sample_dockerfiles/mkdocs-material dst/Dockerfile
    - hard-push-to-repo "dst" "${TEST_REPO_URL}"
    
run test repo pipeline:
  stage: test
  trigger: repos/data-science-lib/templates/docker-image-creator-test-repo
