generate copies:
  image: python:3.11-alpine
  stage: build
  resource_group: integration-test
  before_script:
    - apk update && apk add git
    - pip install -U pip setuptools wheel && pip install -r requirements.txt
    - . utils.sh
  script:
    - copier copy --answers-file copier-answers.yml src dst
    - if [[ -e ${TEST_INPUT_DIR}/Dockerfile ]]; then cp ${TEST_INPUT_DIR}/Dockerfile dst/Dockerfile; fi
    - if [[ -e ${TEST_INPUT_DIR}/test.sh ]]; then cp ${TEST_INPUT_DIR}/test.sh dst/test.sh; fi
    - if [[ -e ${TEST_INPUT_DIR}/determine-docker-image-tags.sh ]]; then cp ${TEST_INPUT_DIR}/determine-docker-image-tags.sh dst/determine-docker-image-tags.sh; fi
    - hard_push_to_repo "dst" "${TEST_REPO_URL}"

run test repo pipeline:
  stage: test
  resource_group: integration-test
  trigger: 
    project: repos/data-science-lib/templates/docker-image-creator-test-repo
    strategy: depend
